services:
  bnnc_composter:
    image: kizyanov/bnnc_composter:latest
    container_name: bnnc_composter
    tty: true
    restart: always
    depends_on:
      - bnnc_alertest
      - bnnc_processor
      - bnnc_nats
    links:
      - bnnc_nats:bnnc_nats
    env_file:
      - .env

  # bnnc_orderest:
  #   image: kizyanov/bnnc_orderest:latest
  #   container_name: bnnc_orderest
  #   tty: true
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - processor
  #     - nats

  # bnnc_balancer:
  #   image: kizyanov/bnnc_balancer:latest
  #   container_name: bnnc_balancer
  #   tty: true
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - processor
  #     - nats
  #   links:
  #    - bnnc_nats:bnnc_nats

  bnnc_processor:
    image: kizyanov/bnnc_processor:latest
    container_name: bnnc_processor
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - bnnc_nats
    links:
      - bnnc_nats:bnnc_nats

  bnnc_alertest:
    image: kizyanov/bnnc_alertest:latest
    container_name: bnnc_alertest
    tty: true
    restart: always
    env_file:
      - .env

  bnnc_nats:
    image: nats:2.10.22-alpine3.20
    container_name: bnnc_nats
    restart: always
    hostname: bnnc_nats
    command: --js
