services:
  bnnc_processor:
    image: kizyanov/bnnc_processor:latest
    build: .
    container_name: bnnc_processor
    tty: true
    restart: always
    # links:
    #   - bnnc_nats:bnnc_nats
    environment:
      - CURRENCY=OP,KCS,WIF,IMX,SUI,APT,ICP,BTC,APE,FRONT

  # bnnc_nats:
  #   image: nats:2.10.22-alpine3.20
  #   container_name: bnnc_nats
  #   restart: always
  #   hostname: nats
  #   command: --js
