services:
  processor:
    image: kizyanov/bnnc_processor:latest
    build: .
    container_name: bnnc_processor
    tty: true
    restart: always
    links:
     - nats:nats
    environment:
      - CURRENCY=OP,KCS,WIF,IMX,SUI,APT,ICP,BTC,APE,FRONT

  nats:
    image: nats:2.10.22-alpine3.20
    container_name: nats
    restart: always
    hostname: nats
    command: --js

