services:
  bnnc_balancer:
    image: kizyanov/bnnc_balancer:latest
    build: .
    container_name: bnnc_balancer
    tty: true
    restart: always
    # links:
    #   - bnnc_nats:bnnc_nats

    # bnnc_nats:
    #   image: nats:2.10.22-alpine3.20
    #   container_name: bnnc_nats
    #   restart: always
    #   hostname: nats
    #   command: --js
